-- insert into PERSON_ADDRESS
DELETE FROM PERSON_ADDRESS;

INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (101,'6649 N Blue Gum St','New Orleans','LA','US','70116');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (102,'4 B Blue Ridge Blvd','Brighton','MI','US','48116');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (103,'8 W Cerritos Ave #54','Bridgeport','NJ','US','8014');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (104,'639 Main St','Anchorage','AK','US','99501');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (105,'34 Center St','Hamilton','OH','US','45011');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (106,'3 Mcauley Dr','Ashland','OH','US','44805');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (107,'7 Eads St','Chicago','IL','US','60632');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (108,'7 W Jackson Blvd','San Jose','CA','US','95111');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (109,'5 Boston Ave #88','Sioux Falls','SD','US','57105');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (110,'228 Runamuck Pl #2808','Baltimore','MD','US','21224');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (111,'2371 Jerrold Ave','Kulpsville','PA','US','19443');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (112,'37275 St  Rt 17m M','Middle Island','NY','US','11953');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (113,'25 E 75th St #69','Los Angeles','CA','US','90034');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (114,'98 Connecticut Ave Nw','Chagrin Falls','OH','US','44023');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (115,'56 E Morehead St','Laredo','TX','US','78045');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (116,'73 State Road 434 E','Phoenix','AZ','US','85013');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (117,'69734 E Carrillo St','Mc Minnville','TN','US','37110');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (118,'322 New Horizon Blvd','Milwaukee','WI','US','53207');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (119,'1 State Route 27','Taylor','MI','US','48180');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (120,'394 Manchester Blvd','Rockford','IL','US','61109');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (121,'6 S 33rd St','Aston','PA','US','19014');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (122,'6 Greenleaf Ave','San Jose','CA','US','95111');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (123,'618 W Yakima Ave','Irving','TX','US','75062');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (124,'74 S Westgate St','Albany','NY','US','12204');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (125,'3273 State St','Middlesex','NJ','US','8846');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (126,'1 Central Ave','Stevens Point','WI','US','54481');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (127,'86 Nw 66th St #8673','Shawnee','KS','US','66218');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (128,'2 Cedar Ave #84','Easton','MD','US','21601');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (129,'90991 Thorburn Ave','New York','NY','US','10011');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (130,'386 9th Ave N','Conroe','TX','US','77301');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (131,'74874 Atlantic Ave','Columbus','OH','US','43215');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (132,'366 South Dr','Las Cruces','NM','US','88011');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (133,'45 E Liberty St','Ridgefield Park','NJ','US','7660');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (134,'4 Ralph Ct','Dunellen','NJ','US','8812');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (135,'2742 Distribution Way','New York','NY','US','10025');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (136,'426 Wolf St','Metairie','LA','US','70002');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (137,'128 Bransten Rd','New York','NY','US','10011');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (138,'17 Morena Blvd','Camarillo','CA','US','93012');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (139,'775 W 17th St','San Antonio','TX','US','78204');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (140,'6980 Dorsett Rd','Abilene','KS','US','67410');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (141,'2881 Lewis Rd','Prineville','OR','US','97754');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (142,'7219 Woodfield Rd','Overland Park','KS','US','66204');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (143,'1048 Main St','Fairbanks','AK','US','99708');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (144,'678 3rd Ave','Miami','FL','US','33196');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (145,'20 S Babcock St','Fairbanks','AK','US','99712');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (146,'2 Lighthouse Ave','Hopkins','MN','US','55343');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (147,'38938 Park Blvd','Boston','MA','US','2128');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (148,'5 Tomahawk Dr','Los Angeles','CA','US','90006');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (149,'762 S Main St','Madison','WI','US','53711');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (150,'209 Decker Dr','Philadelphia','PA','US','19132');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (151,'4486 W O St #1','New York','NY','US','10003');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (152,'39 S 7th St','Tullahoma','TN','US','37388');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (153,'98839 Hawthorne Blvd #6101','Columbia','SC','US','29201');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (154,'71 San Mateo Ave','Wayne','PA','US','19087');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (155,'76 Brooks St #9','Flemington','NJ','US','8822');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (156,'4545 Courthouse Rd','Westbury','NY','US','11590');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (157,'14288 Foster Ave #4121','Jenkintown','PA','US','19046');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (158,'4 Otis St','Van Nuys','CA','US','91405');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (159,'65895 S 16th St','Providence','RI','US','2909');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (160,'14302 Pennsylvania Ave','Huntingdon Valley','PA','US','19006');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (161,'201 Hawk Ct','Providence','RI','US','2904');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (162,'53075 Sw 152nd Ter #615','Monroe Township','NJ','US','8831');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (163,'59 N Groesbeck Hwy','Austin','TX','US','78731');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (164,'2664 Lewis Rd','Littleton','CO','US','80126');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (165,'59 Shady Ln #53','Milwaukee','WI','US','53214');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (166,'3305 Nabell Ave #679','New York','NY','US','10009');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (167,'18 Fountain St','Anchorage','AK','US','99515');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (168,'7 W 32nd St','Erie','PA','US','16502');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (169,'2853 S Central Expy','Glen Burnie','MD','US','21061');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (170,'74 W College St','Boise','ID','US','83707');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (171,'701 S Harrison Rd','San Francisco','CA','US','94104');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (172,'1088 Pinehurst St','Chapel Hill','NC','US','27514');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (173,'30 W 80th St #1995','San Carlos','CA','US','94070');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (174,'20932 Hedley St','Concord','CA','US','94520');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (175,'2737 Pistorio Rd #9230','London','OH','US','43140');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (176,'74989 Brandon St','Wellsville','NY','US','14895');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (177,'6 Kains Ave','Baltimore','MD','US','21215');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (178,'47565 W Grand Ave','Newark','NJ','US','7105');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (179,'4284 Dorigo Ln','Chicago','IL','US','60647');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (180,'6794 Lake Dr E','Newark','NJ','US','7104');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (181,'31 Douglas Blvd #950','Clovis','NM','US','88101');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (182,'44 W 4th St','Staten Island','NY','US','10309');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (183,'11279 Loytan St','Jacksonville','FL','US','32254');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (184,'69 Marquette Ave','Hayward','CA','US','94545');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (185,'70 W Main St','Beachwood','OH','US','44122');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (186,'461 Prospect Pl #316','Euless','TX','US','76040');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (187,'47154 Whipple Ave Nw','Gardena','CA','US','90247');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (188,'37 Alabama Ave','Evanston','IL','US','60201');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (189,'3777 E Richmond St #900','Akron','OH','US','44302');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (190,'3 Fort Worth Ave','Philadelphia','PA','US','19106');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (191,'4800 Black Horse Pike','Burlingame','CA','US','94010');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (192,'83649 W Belmont Ave','San Gabriel','CA','US','91776');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (193,'840 15th Ave','Waco','TX','US','76708');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (194,'1747 Calle Amanecer #2','Anchorage','AK','US','99501');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (195,'99385 Charity St #840','San Jose','CA','US','95110');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (196,'68556 Central Hwy','San Leandro','CA','US','94577');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (197,'55 Riverside Ave','Indianapolis','IN','US','46202');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (198,'7140 University Ave','Rock Springs','WY','US','82901');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (199,'64 5th Ave #1153','Mc Lean','VA','US','22102');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (200,'3 Secor Rd','New Orleans','LA','US','70112');
INSERT INTO PERSON_ADDRESS (person_id, street, city, state, country, zip) VALUES (201,'4 Webbs Chapel Rd','Boulder','CO','US','80303');
